name: chrome

on:
  workflow_call:
    inputs:
      chrome-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
      - run: yarn
      - name: test
        run: |
          wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${{ inputs.chrome-version }}-1_amd64.deb \
            && apt install -y /tmp/chrome.deb \
            && rm /tmp/chrome.deb
          yarn test
